package com.feupsplaza.chat.server.ai;

public interface LLMClient {

    /**
     * Sends a prompt (which may include context and the user's message)
     * to the LLM and returns its response.
     *
     * @param prompt The complete text to send to the LLM.
     * @return The text response generated by the LLM.
     */
   String ask(String prompt);
}
