plugins {
    id 'application'
}

group = 'com.feupsplaza.chat'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
    implementation 'at.favre.lib:bcrypt:0.10.2'
    implementation 'commons-cli:commons-cli:1.11.0'
}

application {
    mainClass = 'com.feupsplaza.chat.Main'
}

run {
    standardInput = System.in
}